"""add student_id to borrow

Revision ID: 0bcb19cbe029
Revises: 
Create Date: 2026-02-02 10:40:40.528965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcb19cbe029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_audit_log')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('classification_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('class_name')

    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('borrowed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('returned_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('borrower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'BORROWED'"))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'borrower', ['borrower_id'], ['id'])
        batch_op.create_foreign_key(None, 'guest_borrower', ['guest_id'], ['id'])
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])
        batch_op.drop_column('due_date')
        batch_op.drop_column('returned_date')
        batch_op.drop_column('borrowed_date')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('returned_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['borrower_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'BORROWED'"))
        batch_op.alter_column('borrower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('returned_at')
        batch_op.drop_column('borrowed_at')
        batch_op.drop_column('book_id')
        batch_op.drop_column('guest_id')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('classification_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.create_table('_alembic_tmp_audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('record_id', sa.INTEGER(), nullable=True),
    sa.Column('old_data', sa.TEXT(), nullable=True),
    sa.Column('new_data', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
