"""Add priority, icon, color to Reminder

Revision ID: 10de14da8b05
Revises: 2719219cb264
Create Date: 2026-05-12 21:47:25.256882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10de14da8b05'
down_revision = '2719219cb264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('icon')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
