"""Add priority, icon, color to Reminder

Revision ID: 7bf01cfdbd06
Revises: 10de14da8b05
Create Date: 2026-05-12 22:10:14.252456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf01cfdbd06'
down_revision = '10de14da8b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
