"""violation

Revision ID: 83696de3eb15
Revises: c6970eb699fb
Create Date: 2026-02-25 13:06:18.746669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83696de3eb15'
down_revision = 'c6970eb699fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('severity_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('violation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_type_id', sa.Integer(), nullable=False),
    sa.Column('borrow_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('date_recorded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrow_id'], ['borrow.id'], ),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guest_borrower.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['violation_type_id'], ['violation_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_late', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_column('days_late')

    op.drop_table('violation')
    op.drop_table('violation_type')
    # ### end Alembic commands ###
