"""Add guest_id to EntryLog, make student_id nullable

Revision ID: a8804054ee2e
Revises: 52941112e48a
Create Date: 2026-02-16 12:04:03.431744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8804054ee2e'
down_revision = '52941112e48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'guest_borrower', ['guest_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
