"""Add guest_id to EntryLog with FK name, make student_id nullable

Revision ID: ebb732efabfb
Revises: a8804054ee2e
Create Date: 2026-02-16 12:07:19.432638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb732efabfb'
down_revision = 'a8804054ee2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_entrylog_guest_id', 'guest_borrower', ['guest_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_entrylog_guest_id', type_='foreignkey')
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
