"""empty message

Revision ID: fba495cdad78
Revises: 4f8ac61cc7b7
Create Date: 2026-01-07 14:07:39.968871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba495cdad78'
down_revision = '4f8ac61cc7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('assecion_number', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=120), nullable=True),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borrower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('middlename', sa.String(length=120), nullable=True),
    sa.Column('borrower_type', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('date_hired', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stdnum', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('middlename', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stdnum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('borrower')
    op.drop_table('book')
    # ### end Alembic commands ###
